<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageId>ManagedBackgroundServices.RCL</PackageId>
    <Title>Managed Background Services Razor Class Library</Title>
    <Version>1.0.1</Version>
    <Authors>Adam O'Neil</Authors>
    <Company>Adam O'Neil</Company>
    <Description>Blazor components for monitoring background job health</Description>
    <Copyright>Copyright (c) 2026 Adam O'Neil</Copyright>
    <PackageProjectUrl>https://github.com/adamfoneil/ManagedBackgroundService</PackageProjectUrl>
    <RepositoryUrl>https://github.com/adamfoneil/ManagedBackgroundService</RepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>    
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ManagedBackgroundServices.Abstractions" Version="1.0.3" />
  </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <None Update="readme.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
